chore: remove redundancies
WillCooter/node-cooter pull request #9
Opened 2022-09-26 15:51 UTC by Joel-Valentine

2022-09-26 16:59 UTC, kritzware approved these changes

2022-09-27 10:31 UTC, ricardofrancoli approved these changes
LGTM!

2022-09-27 10:32 UTC, loicadolphe commented
/bump

2022-09-27 10:35 UTC, loicadolphe approved these changes

2022-09-27 10:36 UTC, WillCooter requested changes
Please provide a description for your PR

2023-03-09 12:24 UTC, closed without merging